export const GET_DOGS = "GET_DOGS";
export const GET_TEMPERAMENTS = "GET_TEMPERSMENTS";
export const GET_DOGS_NAME = "GET_DOGS_NAME";
export const POST_DOGS = "POST_DOGS";
export const FILTER_TEMPERAMENTS = "FILTER_TEMPERAMENTS";
export const FILTER_CREATED = "FILTER_CREATED";
export const GET_DETAILS = "GET_DETAILS";
export const PAGE= "PAGE"
export const GET_DOGS_ERROR = "GET_DOGS_ERROR";
