export const GET_DOGS = "GET_DOGS";
export const GET_TEMPERAMENTS = "GET_TEMPERSMENTS";
export const FILTER_TEMPERAMENTS = "FILTER_TEMPERAMENTS";
export const FILTER_CREATED = "FILTER_CREATED";
export const SORT_BY_NAME = "SORT_BY_NAME";
